# Generated by Django 4.0.5 on 2023-08-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0024_alter_audiorecording_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiorecording',
            name='producer',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
