# Generated by Django 4.0.5 on 2023-08-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0025_audiorecording_producer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiorecording',
            name='recording_date',
            field=models.DateField(),
        ),
    ]
