# Generated by Django 4.0.5 on 2023-08-10 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0026_alter_audiorecording_recording_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiorecording',
            old_name='recording_date',
            new_name='release_date',
        ),
    ]
